// ## This file contains all the images used in the app. Add a new line for each additional image. ## //
// ## The Images path alias is configured in the webpack.config.js.

// ## Branding ## //
export { default as siLogoMark } from "Images/si-brand-mark.svg"
export { default as siLogo } from "Images/logo.svg"
export { default as siLogoWhite } from "Images/si-logo-white.svg"
// ## Branding ## //

// ## Assets ## //
export { default as visa } from "Images/visa.png"
export { default as visa2x } from "Images/visa@2x.png"
export { default as visa3x } from "Images/visa@3x.png"
export { default as mastercard } from "Images/master-card.png"
export { default as mastercard2x } from "Images/master-card@2x.png"
export { default as mastercard3x } from "Images/master-card@3x.png"
export { default as amex } from "Images/amex.png"
export { default as amex2x } from "Images/amex@2x.png"
export { default as amex3x } from "Images/amex@3x.png"
export { default as discover } from "Images/discover.png"
export { default as discover2x } from "Images/discover@2x.png"
export { default as discover3x } from "Images/discover@3x.png"
export { default as payment } from "Images/payment.svg"

export { default as illustration01 } from "Images/illustration-01.svg"
export { default as illustration02 } from "Images/illustration-02.svg"
export { default as illustration05 } from "Images/illustration-05.svg"
export { default as illustration10 } from "Images/illustration-10.svg"
export { default as illustration12 } from "Images/illustration-12.svg"
export { default as illustration14 } from "Images/illustration-14.svg"
export { default as illustration16 } from "Images/illustration-16.svg"
export { default as illustration19 } from "Images/illustration-19.svg"
export { default as illustration19d } from "Images/illustration-19-d.svg"
export { default as illustration20 } from "Images/illustration-20.svg"
export { default as illustration21 } from "Images/illustration-21.svg"
export { default as illustration22 } from "Images/illustration-22.svg"
export { default as illustration28 } from "Images/illustration-28.svg"
export { default as illustration32 } from "Images/illustration-32.svg"
export { default as illustration33 } from "Images/illustration-33.svg"
export { default as illustration34 } from "Images/illustration-34.svg"
export { default as illustration36 } from "Images/illustration-36.svg"
export { default as illustration37 } from "Images/illustration-37.svg"
export { default as illustration40 } from "Images/illustration-40.svg"
export { default as illustration40large } from "Images/illustration40-large.svg"

export { default as rejectionlandscape } from "Images/rejection-landscape.svg"
export { default as search } from "Images/search.svg"
export { default as key } from "Images/key.svg"
export { default as car } from "Images/car.svg"
export { default as infographic2 } from "Images/infographic-2.svg"
export { default as editfield } from "Images/editfield.svg"
export { default as breadcrumbtick } from "Images/breadcrumb-tick.svg"
export { default as breadcrumbtickgrey } from "Images/breadcrumb-tick-grey.svg"
export { default as checkmarksmall } from "Images/checkmark-green-small.svg"
export { default as exsmall } from "Images/ex-red-small.svg"
export { default as yellowcheck } from "Images/yellow-check.svg"
export { default as birthday } from "Images/birthday.svg"
export { default as phone } from "Images/phone.svg"
export { default as ssn } from "Images/ssn.svg"
export { default as license } from "Images/license.svg"
export { default as professionallicense } from "Images/professional-license.svg"
export { default as structure } from "Images/structure.svg"
export { default as addresspin } from "Images/addresspin.svg"
export { default as job } from "Images/job.svg"
export { default as business } from "Images/business.svg"
export { default as cityshort } from "Images/city-short.svg"
export { default as notification } from "Images/notification.svg"
export { default as email } from "Images/email.svg"
export { default as address } from "Images/address.svg"
export { default as lock } from "Images/lock.svg"
export { default as lockbig } from "Images/lock-big.svg"
export { default as arrow } from "Images/arrow.svg"
export { default as information } from "Images/information.svg"
export { default as calendar } from "Images/calendar.svg"
export { default as calendarbig } from "Images/calendar-big.svg"
export { default as person } from "Images/person.svg"
export { default as imgcity } from "Images/city-very-long.png"
export { default as imgcity2x } from "Images/city-very-long@2x.png"
export { default as imgcity3x } from "Images/city-very-long@3x.png"
export { default as linkedin } from "Images/linkedin.png"
export { default as linkedin2x } from "Images/linkedin@2x.png"
export { default as linkedin3x } from "Images/linkedin@3x.png"

export { default as spinner } from "Images/spinner.gif"
export { default as close } from "Images/close.svg"

export { default as fb } from "Images/logo-fb.svg"
export { default as twitter } from "Images/logo-twitter.svg"
export { default as star } from "Images/star.svg"



// ## Assets ## //

